version: "3.9"

services:
  api:
    build: .
    container_name: coindesk-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - AES__Key=${AES_KEY}
      - AES__IV=${AES_IV}
      - RSA__PrivateKeyPath=${RSA_PRIVATE_KEY_PATH}
      - RSA__PublicKeyPath=${RSA_PUBLIC_KEY_PATH}
    networks:
      - coindesk-network

networks:
  coindesk-network:
    external: true
